spring:
  application:
    name: mind-illuminated-backend

google-drive:
  credentials: classpath:google-drive/credentials.json
  parent-folder-id: 1xqFEB3LKctyJ9Q4J0MfkJ0C3zyMu531E

header-token:
  name: ${token.name}
  value: ${token.value}
