spring:
  application:
    name: mind-illuminated-backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}

google-drive:
  credentials: classpath:google-drive/credentials.json
  parent-folder-id: 1xqFEB3LKctyJ9Q4J0MfkJ0C3zyMu531E

header-token:
  name: ${token.name}
  value: ${token.value}
